// PromptKiddie Report Template
// Dark hacker aesthetic with green accents
// Usage: #import "report.typ": *
//        #show: pk-report.with(title: "...", target: "...", ...)

#let pk-green = rgb("#22c55e")
#let pk-green-dim = rgb("#166534")
#let pk-bg = rgb("#0a0f0a")
#let pk-surface = rgb("#141a14")
#let pk-border = rgb("#1e2e1e")
#let pk-text = rgb("#e0e8e0")
#let pk-dim = rgb("#6b7b6b")

#let severity-color(sev) = {
  if sev == "critical" { rgb("#ef4444") }
  else if sev == "high" { rgb("#f97316") }
  else if sev == "medium" { rgb("#eab308") }
  else if sev == "low" { rgb("#3b82f6") }
  else { rgb("#6b7280") }
}

#let pk-report(
  title: "Security Assessment",
  subtitle: none,
  target: none,
  engagement-type: none,
  client: none,
  assessor: none,
  date: none,
  version: "1.0",
  classification: "CONFIDENTIAL",
  body,
) = {
  set page(
    paper: "a4",
    margin: (top: 2.5cm, bottom: 2cm, left: 2.5cm, right: 2.5cm),
    fill: white,
    header: context {
      if counter(page).get().first() > 2 [
        #set text(7pt, font: "Courier New", fill: luma(140))
        #smallcaps[promptkiddie] #h(4pt) // #title
        #h(1fr)
        #date
      ]
    },
    footer: context {
      if counter(page).get().first() > 2 [
        #set text(7pt, font: "Courier New", fill: luma(160))
        #classification
        #h(1fr)
        #text(fill: luma(190))[generated by promptkiddie]
        #h(1fr)
        #counter(page).display() / #context counter(page).final().first()
      ]
    },
  )

  set text(font: "Helvetica Neue", size: 10pt, fill: luma(30))
  set par(leading: 0.7em, justify: false)
  set heading(numbering: "1.1")

  show heading.where(level: 1): it => {
    pagebreak(weak: true)
    v(0.5em)
    set text(15pt, weight: "bold", fill: luma(20))
    it
    v(0.3em)
    line(length: 100%, stroke: 0.5pt + luma(200))
    v(0.3em)
  }

  show heading.where(level: 2): it => {
    v(0.6em)
    set text(12pt, weight: "bold", fill: luma(30))
    it
    v(0.2em)
  }

  show heading.where(level: 3): it => {
    v(0.4em)
    set text(10.5pt, weight: "bold", fill: luma(50))
    it
    v(0.2em)
  }

  // Code blocks: dark background
  show raw.where(block: true): it => {
    set text(8.5pt, font: "Courier New")
    block(
      width: 100%,
      fill: rgb("#0d1117"),
      stroke: 0.5pt + rgb("#30363d"),
      inset: 10pt,
      radius: 3pt,
      breakable: true,
      text(fill: rgb("#c9d1d9"), it),
    )
  }

  show raw.where(block: false): it => {
    box(
      fill: rgb("#f0f0f0"),
      inset: (x: 3pt, y: 1pt),
      radius: 2pt,
      text(8.5pt, font: "Courier New", it),
    )
  }

  // Tables
  set table(
    stroke: 0.5pt + luma(210),
    inset: 7pt,
    fill: (_, y) => if y == 0 { rgb("#f6f8fa") },
  )
  show table.cell.where(y: 0): set text(weight: "bold", size: 8.5pt, font: "Courier New")

  show link: it => text(fill: pk-green-dim, it)

  // ─── Cover Page ─────────────────────────────────────────────

  page(header: none, footer: none, fill: pk-bg)[
    #v(2fr)

    #align(center)[
      #block(width: 80%)[
        // PK logo
        #text(11pt, font: "Courier New", fill: pk-green, weight: "bold")[pk promptkiddie]
        #v(2em)

        #text(28pt, weight: "bold", fill: white)[#title]

        #if subtitle != none [
          #v(0.3em)
          #text(14pt, fill: pk-dim)[#subtitle]
        ]

        #v(1.5em)
        #line(length: 40%, stroke: 1pt + pk-green)
        #v(1.5em)

        #set text(10pt, font: "Courier New", fill: pk-dim)

        #if target != none [
          #text(fill: pk-green)[target:] #text(fill: pk-text)[#target] \
        ]
        #if engagement-type != none [
          #text(fill: pk-green)[type:] #text(fill: pk-text)[#engagement-type] \
        ]
        #if client != none [
          #text(fill: pk-green)[client:] #text(fill: pk-text)[#client] \
        ]
        #if assessor != none [
          #text(fill: pk-green)[assessor:] #text(fill: pk-text)[#assessor] \
        ]
        #if date != none [
          #text(fill: pk-green)[date:] #text(fill: pk-text)[#date] \
        ]
        #text(fill: pk-green)[version:] #text(fill: pk-text)[#version]

        #v(2em)

        #if classification != none [
          #box(
            fill: rgb("#ef4444"),
            inset: (x: 14pt, y: 6pt),
            radius: 2pt,
            text(9pt, font: "Courier New", weight: "bold", fill: white)[#classification],
          )
        ]
      ]
    ]

    #v(3fr)
  ]

  // ─── TOC ────────────────────────────────────────────────────

  outline(title: "Contents", indent: 1.5em, depth: 3)

  body
}

// ─── Components ───────────────────────────────────────────────

#let finding-card(
  title: "",
  severity: "",
  cvss: "",
  vector: none,
  owasp: none,
  attack: none,
  cve: none,
  status: "confirmed",
) = {
  let sev-col = severity-color(severity)

  block(
    width: 100%,
    stroke: (left: 3pt + sev-col, rest: 0.5pt + luma(210)),
    inset: 12pt,
    radius: (right: 3pt),
    breakable: false,
  )[
    #text(12pt, weight: "bold")[#title]
    #v(0.3em)
    #table(
      columns: (1fr, 1fr, 1fr, 1fr),
      [*Severity*], [*CVSS 3.1*], [*Status*], [*Frameworks*],
      [#box(fill: sev-col, inset: (x: 6pt, y: 3pt), radius: 2pt, text(8pt, fill: white, weight: "bold", upper(severity)))],
      [#cvss #if vector != none [\ #text(7pt, fill: luma(140))[#vector]]],
      [#status],
      [
        #if owasp != none [#text(8pt, font: "Courier New")[OWASP: #owasp] \ ]
        #if attack != none [#text(8pt, font: "Courier New")[ATT&CK: #attack] \ ]
        #if cve != none [#text(8pt, font: "Courier New")[CVE: #cve]]
      ],
    )
  ]
}

#let attack-chain(steps) = {
  block(
    width: 100%,
    fill: rgb("#f6f8fa"),
    stroke: 0.5pt + luma(210),
    inset: 12pt,
    radius: 3pt,
  )[
    #set text(9pt, font: "Courier New")
    #for (i, step) in steps.enumerate() [
      #text(fill: pk-green)[#str(i + 1).] #step
      #if i < steps.len() - 1 [
        #v(0.2em)
        #text(fill: luma(180))[ |]
        #v(0.2em)
      ]
    ]
  ]
}

#let severity-table(critical: 0, high: 0, medium: 0, low: 0, info: 0) = {
  table(
    columns: (1fr, 1fr, 1fr, 1fr, 1fr),
    [*Critical*], [*High*], [*Medium*], [*Low*], [*Info*],
    [#text(fill: severity-color("critical"), weight: "bold")[#critical]],
    [#text(fill: severity-color("high"), weight: "bold")[#high]],
    [#text(fill: severity-color("medium"), weight: "bold")[#medium]],
    [#text(fill: severity-color("low"), weight: "bold")[#low]],
    [#text(fill: severity-color("info"), weight: "bold")[#info]],
  )
}

#let evidence-block(caption: none, content) = {
  figure(
    block(
      width: 100%,
      fill: rgb("#0d1117"),
      stroke: 0.5pt + rgb("#30363d"),
      inset: 10pt,
      radius: 3pt,
      text(8.5pt, font: "Courier New", fill: rgb("#c9d1d9"), content),
    ),
    caption: if caption != none { text(9pt, caption) },
    kind: "evidence",
    supplement: "Evidence",
  )
}

#let flag-captured(flag) = {
  block(
    width: 100%,
    fill: rgb("#052e16"),
    stroke: 1pt + pk-green,
    inset: 10pt,
    radius: 3pt,
  )[
    #text(9pt, font: "Courier New", fill: pk-green)[FLAG CAPTURED: ]
    #text(11pt, font: "Courier New", fill: white, weight: "bold")[#flag]
  ]
}
